version: "2.4"

services:
  app:
    build: oilmarket
    restart: unless-stopped
    ports:
      - "2112:2112"
    mem_limit: 512m
    cpus: 1
    pids_limit: 256
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=oilmarket
      - POSTGRES_PASSWORD=oilmarket
      - POSTGRES_DB=oilmarket
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:rox
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
