services:
  caddy:
    image: caddy:2.7.5-alpine
    cpus: 1
    mem_limit: 512M
    pids_limit: 256
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./front:/var/www/neftetochka:ro
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - 8087:8087
    depends_on:
      - app
      - db
  app:
    build: .
    cpus: 2
    mem_limit: 512m
    pids_limit: 16000
    restart: unless-stopped
    environment:
      PG_DSN: "host=db port=5432 user=app password=app dbname=app sslmode=disable"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:rox
      - postgres-data:/var/lib/postgresql/data
volumes:
  caddy-data:
  caddy-config:
  postgres-data:
